name: deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: appengine
    env:
      APP_ENV: ${{ secrets.APP_ENV }}
      APP_HOST: ${{ secrets.APP_HOST }}
      APP_SERVICE: ${{ secrets.APP_SERVICE }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      APP_KEYS: ${{ secrets.APP_KEYS }}
      API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
      ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MIN_INSTANCES: ${{ secrets.MIN_INSTANCES }}
      MAX_INSTANCES: ${{ secrets.MAX_INSTANCES }}
      TARGET_CPU_UTILIZATION: ${{ secrets.TARGET_CPU_UTILIZATION }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
      GCS_BASE_PATH: ${{ secrets.GCS_BASE_PATH }}
      GCS_BASE_URL: ${{ secrets.GCS_BASE_URL }}
      GCS_PUBLIC_FILES: ${{ secrets.GCS_PUBLIC_FILES }}
      GCS_UNIFORM: ${{ secrets.GCS_UNIFORM }}
      GCS_SERVICE_ACCOUNT: ${{ secrets.GCP_SA_KEY }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}

    steps:
      - uses: actions/checkout@v6

      - name: create yaml
        run: ./create_yaml.sh

      - name: auth
        uses: google-github-actions/auth@v3
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: deploy
        uses: google-github-actions/deploy-appengine@v3
        with:
          project_id: "${{ secrets.GCP_PROJECT }}"
          deliverables: app.yaml
